name: klarto_server
description: The backend API for the Klarto application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  postgres: ^2.6.1
  bcrypt: ^1.1.3
  dotenv: ^4.2.0
  crypto: ^3.0.3
  http: ^1.1.0
  dart_jsonwebtoken: ^2.12.0
  shelf_multipart: ^1.0.0
  shelf_static: ^1.1.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0